"""Durable SQLite persistence for the debate knowledge base.

The database stores structured metadata and original text only. It is fully
rebuildable from the source archive and is independent of the embedding and
vector-search layers that arrive in later milestones.
"""

from debate_engine.storage.chunks import (
    LexicalSearchHit,
    LexicalSearchUnavailableError,
    build_match_expression,
    count_chunks,
    count_chunks_by,
    delete_chunk,
    delete_chunks_for_document,
    get_chunk,
    get_chunks_for_document,
    list_chunks,
    replace_chunks_for_document,
    search_chunks,
    update_duplicate_groups,
    upsert_chunk,
    upsert_chunks,
)
from debate_engine.storage.db import (
    SCHEMA_VERSION,
    clear_database,
    connect,
    create_schema,
    database_connection,
    drop_schema,
    foreign_keys_enabled,
    full_text_search_available,
    index_names,
    initialize_database,
    rebuild_full_text_index,
    recreate_database,
    resolve_database_path,
    schema_version,
    table_names,
    transaction,
)
from debate_engine.storage.documents import (
    count_documents,
    count_documents_by,
    delete_document,
    find_documents_by_filename,
    get_document,
    list_documents,
    upsert_document,
    upsert_documents,
)
from debate_engine.storage.duplicates import (
    count_duplicate_group_members,
    count_duplicate_groups,
    count_duplicate_groups_by,
    delete_duplicate_group,
    get_duplicate_group,
    get_duplicate_groups_for_chunk,
    get_duplicate_members,
    list_duplicate_groups,
    replace_duplicate_groups,
    upsert_duplicate_group,
    upsert_duplicate_groups,
)

__all__ = [
    "LexicalSearchHit",
    "LexicalSearchUnavailableError",
    "SCHEMA_VERSION",
    "build_match_expression",
    "clear_database",
    "connect",
    "count_chunks",
    "count_chunks_by",
    "count_documents",
    "count_documents_by",
    "count_duplicate_group_members",
    "count_duplicate_groups",
    "count_duplicate_groups_by",
    "create_schema",
    "database_connection",
    "delete_chunk",
    "delete_chunks_for_document",
    "delete_document",
    "delete_duplicate_group",
    "drop_schema",
    "find_documents_by_filename",
    "foreign_keys_enabled",
    "full_text_search_available",
    "get_chunk",
    "get_chunks_for_document",
    "get_document",
    "get_duplicate_group",
    "get_duplicate_groups_for_chunk",
    "get_duplicate_members",
    "index_names",
    "initialize_database",
    "list_chunks",
    "list_documents",
    "list_duplicate_groups",
    "rebuild_full_text_index",
    "recreate_database",
    "replace_chunks_for_document",
    "replace_duplicate_groups",
    "resolve_database_path",
    "schema_version",
    "search_chunks",
    "table_names",
    "transaction",
    "update_duplicate_groups",
    "upsert_chunk",
    "upsert_chunks",
    "upsert_document",
    "upsert_documents",
    "upsert_duplicate_group",
    "upsert_duplicate_groups",
]
